import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { MainNavbar } from "@/components/main-navbar";
import Image from "next/image";
import { InicioMenubar } from "@/components/inicio-menubar";
import { ModeToggle } from "@/components/toggle-theme";
import { MainMenu } from "@/components/main-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div>
            <MainNavbar></MainNavbar>
            <div className="mx-auto mt-8">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
